# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5156c8ffb8c0cbba4a50a15b6761bf8d3d3ce6b8ed2d038574d7f0ae1c5d257fea12cdf65417e0edc5c97d83108142f1098e80d1a137f15b433f703868a332dc

test:
  secret_key_base: 5a9e615bc5b59eb29957b4458f2918165e95f815ec051de3b6382b6bb53c2821f657b31eb27bc33c99c6de5f1404e00219a247a8276eb427ec92292679609c48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
